server:
  port: 8888
  
spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/juan759/config-data.git 
          search-paths: config-data/api
          default-label: "master"
          
  security:
    user:
      name: root
      password: adminadmin
